sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
      - python2.6
      - python3.5
before_install:
  - git config user.name "ansible"
  - git config user.email "ansible@ansible.com"
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then git rebase $TRAVIS_BRANCH; fi;
install:
  - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
  - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
script:
  - python2.4 -m compileall -fq -x 'cloud/|monitoring/zabbix.*\.py|/dnf\.py|/layman\.py|/maven_artifact\.py|clustering/(consul.*|znode)\.py|notification/pushbullet\.py|database/influxdb/influxdb.*\.py' .
  - python2.6 -m compileall -fq .
  - python2.7 -m compileall -fq .
  - python3.4 -m compileall -fq system/at.py
  - python3.5 -m compileall -fq system/at.py
  - ansible-validate-modules .
  #- ./test-docs.sh extras
